packages:
  - '__build__'

allowBuilds:
  '@arts/github-release-browser': true
  '@arts/release-deploy-core': true
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  fs-ext-extra-prebuilt: true
